version: 0.0
os: linux
files:
   - source: /
     destination: /var/www
permissions:
   - object: /var/www
     pattern: "**"
     owner: ec2-user
     mode: 755
     type:
       - file
hooks:
  AfterInstall :
    - location: deployment/application-setup.sh
      timeout: 3600
  ApplicationStart:
    - location: deployment/application-start.sh
      timeout: 3600


