version: 0.0
os: linux
files:
   - source: config/
     destination: /var/www/beecompanion/config/
   - source: deployment/
     destination: /var/www/beecompanion/deployment/
   - source: dist/
     destination: /var/www/beecompanion/dist/
   - source: server/
     destination: /var/www/beecompanion/api/
   - source: ./package.json
     destination: /var/www/beecompanion/
permissions:
   - object: /var/www
     pattern: "**"
     owner: root
     mode: 755
     type:
       - file
hooks:
  ApplicationStart:
    - location: deployment/application-start.sh
      timeout: 3600
      runas: root


