version: 0.0
os: linux
files:
   - source: /
     destination: /var/www
permissions:
   - object: /var/www
     pattern: "**"
     owner: root
     mode: 755
     type:
       - file
hooks:
  ApplicationStart:
    - location: deployment/application-start.sh
      timeout: 3600
      runas: root


